### ISSUE TITLE
FixError types should implement some more basic traits

### ISSUE THREAD

**Issue by GKnirps** [austinhartzheim/rust-gtin-validate#5]
Hi,
for some of my use cases, it would be nice if the FixError-types (such as gtin14::FixError) implemented some more of the basic traits. I would suggest Clone, PartialEq, Eq, Hash and maybe Copy. Right now, they only implement Debug.

Are there any reasons against this?

**Comment by austinhartzheim** [comment]
Sounds good to me. I'd happily merge a PR to add that.

Out of curiosity, what would you be using Hash and Copy for?

**Comment by GKnirps** [comment]
Generally, I think it is a good idea to derive those basic traits for structs and enums, since users of a crate can't implement them on their own, but may want to derive those traits for their own data structures that contain data structures from a crate.

Personally, I don't really need Hash and Copy, but I can imagine someone might want to put it in a HashMap for some reason. Since the maintenance cost for most of these traits is very low if they are derived, it should be no problem implementing them.

One should be careful with copy though, because adding a non-copyable variable to the enum/struct later will result in a breaking change.

**Comment by austinhartzheim** [comment]
Yeah, it makes sense to implement those traits preemptively. I was wondering if you had a use case specifically, because it seems somewhat strange (although not impossible) to need those on an error type.

PR merged. I'll cut a release.

**Comment by GKnirps** [comment]
thanks

**Comment by MggMuggins** [comment]
Given that `FixError` is an error type, it would be nice if it implemented `std::error::Error`. That would make it play nicely with `anyhow` and friends. I may open a PR.
